import kotlin.browser.document



fun main(args: Array<String>)
{
    val EA_ADDRESS = "Electronic Arts Corporation - 250 Redwood Shores Parkway, Redwood City, CA. 94065 "
    val EXIT_CERTIFIED_TRAINING_DESC = "•Via official training partner Global Knowledge; attended a 3-day bootcamp instructor led training and gained certification"

    //console debug info
    println("* * * DEBUG: This should appear in the console! * * *")

    //create elements programmatically using DOM API, then assign to variable
    val root = document.getElementById("root")
    val div = document.createElement("div")
    var h1 = document.createElement("h1")


    h1.textContent = "Bryan Edward Cutkelvin"
    div.appendChild(h1)

    var textNode = document.createTextNode("b.cutkelv@gmail.com")
    div.appendChild(textNode)
    var linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("www.bryancutkelvin.com")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("https://www.linkedin.com/in/mrbcut")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("https://github.com/MrBCut")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("EXPERIENCE")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("3/2017 – 7/2020")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("QA ENGINEER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Yummly Inc. 610 Walnut St. Redwood City, CA. 94063")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> QA Manager: Vito D'Alessandro III (916) 690-6906; Human Resources Manager: Nancy Nichols nany.nichols@yummly.com")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Create and update automaton test suites and test cases performing on websites, databases and API calls using Kotlin, Java, JavaScript, Selenium, TestNg, XML, Restful API.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Utilize knowledge of QA methodology and testing techniques and approaches of website infrastructure. Resources including Jira for project Monitoring and defect reporting.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Use of Jenkins as CI process for Continuous Deployment delivery. Including scripting using JenkinsFile, creating environment domains, Releasing production code in pipeline and debugging Groovy files.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Use of GitHub to commit, merge and pull repository code. Use of UNIX command line for basic navigation and file manipulation.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Utilize Amazon Web Services to verify existence of Jenkins created environment boxes utilizing series including Cloud Formation, Route53, EC2, Amazon S3, CloudWatch. Received training and AWS certification(aws.amazon.com/verification(validation# 8P9RBX3CJNEEQE92) ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Work with cross functional teams including back end, mobile, design marketing and management for communication and decision engagement for problem solving, urgent action notices and resolve and decision making")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("3/2016 – 3/2017")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("TEST DESIGNER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Sony Computer Entertainment America – 2207 Bridgepointe Pkwy.San Mateo, CA 94404")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> Yoh Staffing Resource Manager: Adriana Armstrong (650)655-7480; Format QA Manager: Doron Griss (650)655-8141; Format QA Supervisor Aaron Kulka (650)655-1627")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Primary duties performing as a Test Designer in FQA Compatibility group. Defined test criteria for software: PlayStation VR, PlayStation Now, PlayStation Store, PlayStation Network and Gaikai and any related hardware or software compatibility. Ensured Test Design addressed product team implementations and requirements of features detailed in GitHub repository check-ins and fork builds as confirmed by Redmine ticket requests to verify expected behaviors.    ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Performed supplemental duties as a Quality Assurance Analyst executing test cases based on Test Designs and developer documentation. Regressed, maintained and updated existing test cases on new and deprecated features. Worked closely with QA managers and QA Analyst team members located on and off-site. Created automation programs to perform as tools.      ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Experience with digital commerce systems of micro transactions on online services. Product Management Tool portal: create, modify and manage products and services part of Sony Entertainment Network catalog.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("5/2015 - 3/2016")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("WEB DEVELOPER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("BeTheMatch.org San Francisco, CA.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contact -> Community Engagement Representative: Jennifer Eisenbud Sawle (510) 427-9336")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•As a Web site developer, created, update and monitor a website for a sickle cell patient www.erianasmith.com using HTML5, CSS3, PHP" +
            "and WordPress. Site serves purpose for gathering registrants for patient and provides information on Sickle Cell disease. Includes link to" +
            "a GoFundMe page that I also administer and other resources for patient events, facts and resources.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Participate in volunteer work to spread awareness of a large need for bone marrow registrants to help cure people of diseases such as" +
            "sickle cell anemia and other blood cancers and Awareness Advocate under supervision of Community Engagement Representatives.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Help with greetings and informing community" +
            "patrons of opportunities for cure, distribution of materials and information, mentioning monetary contributions, booth set up and tear downs" +
            "and following any additional instructions.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("8/2013 - 3/2015")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("WEB QA ENGINEER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Perfect World Entertainment, Inc. Redwood City, CA 94065")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> Lead/Release Engineer Supervisor: Andrew Patrick (650)703-6601, Web QA Engineer: Vito D'Alessandro (916)390-6906")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Programmed automation test in Java/J2EE language framework using Selenium automation framework including Joint and TestNG unit testing, with XML deployment and log result generation for build verification on Jenkins continuous integration servers on VMWare platform. testing. Also, programming in PHP performing PHPUnit testing  API data with REST calls")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Created Javadoc documentation for automation suite code base used by Web QA Engineer on and offsite. Created Page Load Performance suite and testing using Phantom JavaScript library that performed page load performance statistics according to YSLowscores and standards. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Work with web development and game development teams to create and support test planning and building automation test suites for identify defects and verifying correct functionality of frequent test cycles as part of product release planning delivery dates guided by an Agile methodology.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("1/2008 – 8/2013")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("QUALITY ANALYST")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EA_ADDRESS)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> QA Project Manager: Mark “Bones” Johnson (650)628-5128, Producer: Peter Wang (650)267-3658 QA Test Lead: Kevin Lee (650)628-2830")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•As a Quality Analyst, creating programs for automation framework driven in Java language for Automation Infrastructure Development. Created automation programs using Selenium WebDriver framework and using Java, Joint, POI, XML, and ANT technologies. Creation of a full automation framework to test micro content website features and acceptance test, of front end and back end functionality to signoff on build integrity. Compiled      pass or fail test cases results in a summary log and generated email reports to Development Directors, Producers, Engineers and QA managers and ions of a master account of over 3500 entitlements were verified and created log files to perform pass/fail test run results. Also, created an automation program to perform site crawling by validating URL were not accessible through XSS hacks or illegal URL redirects and permission only pages were not accessible. Good Exposure using Selenium IDE as well in Java/Junit programming.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Website troubleshooting skills with understanding of Java, UNIX, XML, MySQL and Tomcat functionality and familiarity with Client/Server communications and detection and thwarting of hacking methods such as SQL injection, Cross Site Scripting, JavaScript, MySQL/PHP, Selenium and more. " +
            "QA testers. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Created Selenium WebDriver 2 scripts to perform automation regressions for various tasks including nightly download automation queues where regress")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("4/2007 – 1/2008")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("SENIOR QUALITY ASSURANCE TESTER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EA_ADDRESS)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> Project Leads: Sarah Holding (650)628-7220, Carlos Moreira (650)628-5006, QA Manager Matt Brown (650)628-5939, HR manager Ericka Sykes (650)628-7805 x87805")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Quality Assurance Game Software Tester on PC titles: Sims 2 EP7: FreeTime and Sims 2 SP5: Kitchen & Bath Interior Designs.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Quality Assurance Game Software Tester on PC title SimCity: Societies.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Quality Assurance Game Tuning Software Tester on Nintendo Wii title MySims.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Operation of Nintendo Wii Development Kit “NDEV” console and game architecture troubleshooting skills with understanding of C++, Lua and Codewarrior IDE")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Regressions of Gameplay test functionality and defects into Dev Track and DevTest Databases. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("9/2006 - 4/2007")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("QUALITY ASSURANCE TESTER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Sony Computer Entertainment of America 919 E. Hillsdale Blvd. 2nd Floor, Foster City, CA. 94404 ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> QA Multimedia Supervisor Randy Blake, (650)655-8038, QA Multimedia Manager: Doron Griss, (650) 655-8141")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Quality Assurance Console Tester of Playstation 3 using PS3 development kit and emulator software. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Regressions of test functionality of PSP (Playstation Portable) handheld and Playstation 2 console. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Interact with Bugzilla database to enter defects and document new bugs for Playstation 3 library backward compatibility. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•PS3 Dev kit operations with understanding of Shell and C script commands in Linux OS environment")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("5/2005 – 2/2006")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("SOFTWARE QUALITY ASSURANCE TESTER")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EA_ADDRESS)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Contacts -> Project Lead Jim Larimore (650) 628 3834")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Quality Assurance Game Software Tester on PC titles The Sims 2: Open for Business, The Sims 2: Nightlife, The Sims 2 Holiday Party Pack, and The Sims Complete Collection.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Automation scripting of release builds using Perl, XML, HTML format and loading results into server using SQL.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Entering identified Object Errors and Gameplay defects into DevTrack.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("EDUCATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("February 2019")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("AMAZON WEB SERVICES: CLOUD PRACTITIONER ESSENTIALS CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("450 Sansome Street #600 San Francisco, CA. 94111")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Earned official AWS Cloud Practitioner Essentials certification (aws.amazon.com/verification (validation# 8P9RBX3CJNEEQE92) demonstrating knowledge and operation of AW products and services. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Knowledge of practice demonstrating AWS Cloud fundamental and best practices of deploying and operating including architectures, pricing and technical assistance.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("June  2013")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("BACHELORS OF SCIENCE DEGREE")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("California State University East Bay 25800 Carlos Bee Blvd. Hayward, CA. 94542 (510) 886-5000 ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Major: Computer Science.  Studies: Software Engineering and Development in Java and C++ and other programming languages")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("June 2019")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("ICND1 V3.0 INTERCONNECTING CISCO NETWORKING DEVICES, PART 1 CERTIFICATION & TRAINING")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Via official training partner Global Knowledge attended a 5-day bootcamp instuctor led training and gained certification")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Training and instruction on: how to install, operate, configure, and verify a basic IPv4 and IPv6 network, including configuring a LAN switch, configuring an IP router, managing network devices, and identifying basic security threats")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("May 2019")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("TROUBLESHOOTING TCP/IP NETWORKS WITH WIRESHARK")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EXIT_CERTIFIED_TRAINING_DESC)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Training and instruction on: how to Learn to use Wireshark to identify and fix your TCP/IP network performance problems s  instructor-led training from a Wireshark subject matter expert. This course also includes official Wireshark study guides, and hands-on training with live labs.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("January 2019")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("ARCHITECTING ON AWS TRAINING & CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EXIT_CERTIFIED_TRAINING_DESC)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Training and instruction on: use of the AWS Cloud by understanding AWS services and how services offer solutions,  best practices, design patterns and labs architecting solutions for storage, web/app servers, databases, CloudFront, DNS, Compute, Networking, Storage, Elastic Beanstalk. ")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("October 2017")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("SYSTEMS OPERATIONS ON AWS TRAINING & CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EXIT_CERTIFIED_TRAINING_DESC)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Training and instruction on:  covered AWS features and tools related to configuration and deployments, as well as common techniques used throughout industry for configuring and deploying systems.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("July 2017")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("TECHNICAL ESSENTIALS ON AWS TRAINING & CERTIFICATION TRAINING")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode(EXIT_CERTIFIED_TRAINING_DESC)
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Training and instruction on:  Introduction to AWS products, services, and common solutions. Fundamentals identifying AWS services. Certifications earned: AWS Technical Essentials")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("March 2016")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("FULL STACK JAVA WEB DEVELOPMENT CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("Amfasoft Technical Training 39510 Paseo Padre Pkwy #380 Fremont, CA 94538 (510)745-9158")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Completed a 300 hour program instructing web application development with focus on Java, J2EE, XML, and Oracle Technologies. Earning certificate as a Java Web Application Developer.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("October 2015")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("FRONT END WEB DEVELOPMENT CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("AcademyX Computer Training 601 Montgomery St. Suite 409 San Francisco, CA 94111 (415) 392-8024")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("•Completed 108 hours of instruction and training covering web development in technologies including WordPress, HTML5, CSS3, JavaScript, JQuery, Bootstrap.js and creating responsive web pages.")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    textNode = document.createTextNode("May 2013")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("JAVA PROGRAMMING CERTIFICATION")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    textNode = document.createTextNode("California State University East Bay Continuing Education Services 25800 Carlos Bee Blvd. Hayward, CA. 94542 (510) 886-5000")
    div.appendChild(textNode)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)
    linebreak = document.createElement("br")
    div.appendChild(linebreak)

    //attach <div> as child of root
    root!!.appendChild(div)
}